# 
# Synthesis run script generated by Vivado
# 

set_msg_config  -ruleid {1}  -id {DRC LUTLP-1}  -string {{ERROR: [DRC LUTLP-1] Combinatorial Loop Alert: 29 LUT cells form a combinatorial loop. This can create a race condition. Timing analysis may not be accurate. The preferred resolution is to modify the design to remove combinatorial logic loops. If the loop is known and understood, this DRC can be bypassed by acknowledging the condition and setting the following XDC constraint on any net in the loop: 'set_property ALLOW_COMBINATORIAL_LOOPS TRUE [net_nets <myHier/myNet>'. The cells in the loop are: Controller/temp1_reg[0]_i_2, Controller/temp1_reg[0]_i_3, Controller/temp1_reg[0]_i_4, Controller/temp2_reg[0]_i_8, Controller/temp2_reg[0]_i_9, Controller/temp2_reg[0]_i_10, Controller/temp3_reg[0]_i_10, Controller/temp3_reg[0]_i_11, Controller/temp3_reg[0]_i_12, Controller/temp3_reg[2]_i_39, Controller/temp3_reg[2]_i_40, Controller/temp3_reg[2]_i_41, Controller/temp3_reg[2]_i_63, Controller/temp3_reg[2]_i_64, Controller/temp3_reg[2]_i_65... and (the first 15 of 29 listed).}}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/EE_Classes/EE324_Projects/Reaction_Timer/reaction.cache/wt [current_project]
set_property parent.project_path C:/EE_Classes/EE324_Projects/Reaction_Timer/reaction.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/EE_Classes/EE324_Projects/Reaction_Timer/reaction.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/EE_Classes/EE324_Projects/Reaction_Timer/reaction.srcs/sources_1/new/_controller.v
  C:/EE_Classes/EE324_Projects/Reaction_Timer/reaction.srcs/sources_1/new/clkDvr.v
  C:/EE_Classes/EE324_Projects/Reaction_Timer/reaction.srcs/sources_1/new/counter.v
  C:/EE_Classes/EE324_Projects/Reaction_Timer/reaction.srcs/sources_1/new/sev_seg_display.v
  C:/EE_Classes/EE324_Projects/Reaction_Timer/reaction.srcs/sources_1/new/reaction.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/EE_Classes/EE324_Projects/Reaction_Timer/reaction.srcs/constrs_1/new/basys.xdc
set_property used_in_implementation false [get_files C:/EE_Classes/EE324_Projects/Reaction_Timer/reaction.srcs/constrs_1/new/basys.xdc]


synth_design -top reaction -part xc7a35tcpg236-1


write_checkpoint -force -noxdef reaction.dcp

catch { report_utilization -file reaction_utilization_synth.rpt -pb reaction_utilization_synth.pb }
