# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/fer/Desktop/EE214/214/project_3/project_3.cache/wt [current_project]
set_property parent.project_path C:/Users/fer/Desktop/EE214/214/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/fer/Desktop/EE214/214/project_3/project_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/fer/Desktop/EE214/214/project_3/project_3.srcs/sources_1/new/clkDvr.v
  C:/Users/fer/Desktop/EE214/214/project_3/project_3.srcs/sources_1/new/controller.v
  C:/Users/fer/Desktop/EE214/214/project_3/project_3.srcs/sources_1/new/counter.v
  C:/Users/fer/Desktop/EE214/214/project_3/project_3.srcs/sources_1/new/sev_seg_display.v
  C:/Users/fer/Desktop/EE214/214/project_3/project_3.srcs/sources_1/new/stopwatch.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/fer/Desktop/EE214/214/project_3/project_3.srcs/constrs_1/new/basys.xdc
set_property used_in_implementation false [get_files C:/Users/fer/Desktop/EE214/214/project_3/project_3.srcs/constrs_1/new/basys.xdc]


synth_design -top stopwatch_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef stopwatch_top.dcp

catch { report_utilization -file stopwatch_top_utilization_synth.rpt -pb stopwatch_top_utilization_synth.pb }
