# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/EE_Classes/EE324_Projects/Stopwatch/stopwatch.cache/wt [current_project]
set_property parent.project_path C:/EE_Classes/EE324_Projects/Stopwatch/stopwatch.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/EE_Classes/EE324_Projects/Stopwatch/stopwatch.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/EE_Classes/EE324_Projects/Stopwatch/stopwatch.srcs/sources_1/new/clk_div.v
  C:/EE_Classes/EE324_Projects/Stopwatch/stopwatch.srcs/sources_1/new/controller.v
  C:/EE_Classes/EE324_Projects/Stopwatch/stopwatch.srcs/sources_1/new/counter.v
  C:/EE_Classes/EE324_Projects/Stopwatch/stopwatch.srcs/sources_1/new/sev_seg_display.v
  C:/EE_Classes/EE324_Projects/Stopwatch/stopwatch.srcs/sources_1/new/Stopwatch_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/EE_Classes/EE324_Projects/Stopwatch/stopwatch.srcs/constrs_1/new/basys.xdc
set_property used_in_implementation false [get_files C:/EE_Classes/EE324_Projects/Stopwatch/stopwatch.srcs/constrs_1/new/basys.xdc]


synth_design -top Stopwatch_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Stopwatch_top.dcp

catch { report_utilization -file Stopwatch_top_utilization_synth.rpt -pb Stopwatch_top_utilization_synth.pb }
